// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'run FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUje5ZiEzt2lXaixxA3hEVoLSGHHm9Rv0',
    appId: '1:71535756864:web:90ed7428cae1bc0c86c1a5',
    messagingSenderId: '71535756864',
    projectId: 'movies-app-939af',
    authDomain: 'movies-app-939af.firebaseapp.com',
    storageBucket: 'movies-app-939af.firebasestorage.app',
    measurementId: 'G-KEF7825JN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQyjACqTMAlTr2uoAmcsA3DKOWbefxk0I',
    appId: '1:71535756864:android:bfb0207a2427c11b86c1a5',
    messagingSenderId: '71535756864',
    projectId: 'movies-app-939af',
    storageBucket: 'movies-app-939af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9UTYTjsBD1rykkJmBZNLVCSlpbh45LhM',
    appId: '1:71535756864:ios:405d28d2b1528acd86c1a5',
    messagingSenderId: '71535756864',
    projectId: 'movies-app-939af',
    storageBucket: 'movies-app-939af.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = ios;

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUje5ZiEzt2lXaixxA3hEVoLSGHHm9Rv0',
    appId: '1:71535756864:web:0b66bee720a2ef0186c1a5',
    messagingSenderId: '71535756864',
    projectId: 'movies-app-939af',
    authDomain: 'movies-app-939af.firebaseapp.com',
    storageBucket: 'movies-app-939af.firebasestorage.app',
    measurementId: 'G-HPRZ1F6NRG',
  );
}
